const USERS = [
    {
        id: 0,
        firstName: 'Claire',
        lastName: 'Roberts',
        password: 'idk',
        email: 'lalala@gmail.com',
        phone: 2292292299,
        stars: 3,
    },
    {
        id: 1,
        firstName: 'Peter',
        lastName: 'Smith',
        password: 'idk',
        email: 'lalala@gmail.com',
        phone: 2292292299,
        stars: 0,
    },    
    {   id: 2,
        firstName: 'Alex',
        lastName: 'Dinao',
        password: 'idk',
        email: 'lalala@gmail.com',
        phone: 2292292299,
        stars: 5,
    },    
    {   id: 3,
        firstName: 'Jenna',
        lastName: 'Cauldwell',
        password: 'idk',
        email: 'lalala@gmail.com',
        phone: 2292292299,
        stars: 3,
    },    
    {   id: 4,
        firstName: 'Wilo',
        lastName: 'Lopez',
        password: 'idk',
        email: 'lalala@gmail.com',
        phone: 2292292299,
        stars: 4,
    },    
    {   id: 5, 
        firstName: 'Briggita',
        lastName: 'Faraneva',
        password: 'idk',
        email: 'lalala@gmail.com',
        phone: 2292292299,
        stars: 2,
    },
];