export const CLASSES_FETCH_REQUEST = "CLASS_FETCH_REQUEST";
export const CLASSES_FETCH_SUCCESS = "CLASS_FETCH_SUCCESS";
export const CLASSES_FETCH_FAIL = "CLASS_FETCH_FAIL";

export const CLASS_FEATURED_FETCH_REQUEST = "CLASS_FETCH_REQUEST";
export const CLASS_FEATURED_FETCH_SUCCESS = "CLASS_FETCH_SUCCESS";
export const CLASS_FEATURED_FETCH_FAIL = "CLASS_FETCH_FAIL";

